/*
 * biz_error_code.h — Driver error codes (from hp640 SPL).
 */

#ifndef _BIZ_ERROR_CODE_H_
#define _BIZ_ERROR_CODE_H_

typedef enum {
    BIZ_SUCCESS = 0,
    BIZ_ERR_NORMAL,
    BIZ_ERR_CLI_PARAM,
    BIZ_ERR_EMMC_STATE_TIMEOUT,
    BIZ_ERR_EMMC_INIT,
    BIZ_ERR_EMMC_SET_BLK_LEN,
    BIZ_ERR_EMMC_CMD_TIMEOUT,
    BIZ_ERR_EMMC_CMD_CRC,
    BIZ_ERR_EMMC_DATA_TIMEOUT,
    BIZ_ERR_EMMC_DATA_CRC,
    BIZ_ERR_EMMC_DATA_SIZE,
    BIZ_ERR_EMMC_TUNING_FAILED,
    BIZ_ERR_EMMC_DATA_TIMEOUT_SOFT,
    BIZ_ERR_EMMC_DLL_SCAN_FAILED,
    BIZ_ERR_FLASH_INIT,
    BIZ_ERR_FLASH_WRITE_CHECK,
    BIZ_ERR_PRIM_ID,
    BIZ_ERR_PRIM_PARAM,
    BIZ_ERR_PRIM_TIMEOUT,
    BIZ_ERR_PRIM_LOOP_TAG,
    BIZ_ERR_END,
} biz_err_code_t;

#endif /* _BIZ_ERROR_CODE_H_ */
