from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd,
           cwd + r'/../../pcie/ep',
           cwd + r'/../../../board_pkgs/rpmsg-lite/lib/include']

group = DefineGroup('rpmsg-net', src, depend = ['BOARD_PKG_USING_RPMSG_LITE', 'RT_USING_LWIP', 'BSP_USING_RPMSG_NET'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')