from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd,
           cwd + r'/../../packages/rpmsg-lite-latest/lib/include']

group = DefineGroup('rpmsg-net', src, depend = ['PKG_USING_RPMSG_LITE', 'RT_USING_LWIP'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')