import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, os.path.join(cwd, '..', '..')]

if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, 'mii.c')
    SrcRemove(src, 'synopGMAC.c')
    SrcRemove(src, 'synopGMAC_Dev.c')
    SrcRemove(src, 'synopGMAC_plat.c')

group = DefineGroup('Drivers', src, depend = ['BSP_USING_GMAC'], CPPPATH = CPPPATH)


Return('group')
