from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*.S')

# pre_entry.S only needed for BL21 mode (EL3 bootwrapper initialization)
# BL22 mode: bootwrapper already done EL transition, skip pre_entry.S
if GetDepend('BSP_USING_HP232X_BL22'):
    SrcRemove(src, ['pre_entry.S'])

# gic_group_config.c only needed for GIC debug mode
if GetDepend('RT_BSP_GIC_DBG') == False:
    SrcRemove(src, ['gic_group_config.c'])

CPPPATH = [cwd, str(Dir('#'))]

if GetDepend('BSP_USING_SYSCTL_CLK'):
    src += ['clock/drv_sysctl_lite.c']
    CPPPATH += [os.path.join(cwd, 'clock')]

group = DefineGroup('driver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
