from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*.S')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('driver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
