from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('rpsh', src, depend = [''], CPPPATH = CPPPATH)

Return('group')