from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('rpsh', src, depend = ['BSP_USING_RPSH', 'BSP_USING_RPMSG_NET'], CPPPATH = CPPPATH)

Return('group')