# Aggregate net sub-drivers (gmac, rpmsg-net, ...)
from building import *
import os

cwd = GetCurrentDir()
objs = []
for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
